In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
#Casting a list as an array and vector

np.array(my_list)

array([1, 2, 3])

In [4]:
list = [[1,2,3], 
        [3,4,5], 
        [6,7,8]]
list
arr = np.array(list
)
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
#Creating a numpy array

arr1 = np.arange(0, 10,)
print(arr1)
#adding step size
arr2 = np.arange(10, 20, 2)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]


In [29]:
#Creating an a matrix containing zeros

arr1 = np.zeros((10,10))
print(arr1)
print("\n")
arr2 = np.ones((3,7))
print(arr2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [7]:
#Creating equally spaced numbers using linspace

np.linspace(10, 20, 3)
#Returns a one dimensional vector with 3 numbers which are equally sapced from each other

array([10., 15., 20.])

In [32]:
#Taking random numbers between 0 and 1
arr1 = np.random.rand(5)
print(arr1)
print("\n")
#return 4 random numbers scattered around 0. They can be negative too
arr = np.random.randn(4) 
print(arr)
print("\n")


arrMean = arr.mean() #calculate the mean of the array
print(arrMean)
print("\n")

a = np.random.randn(4,4)
# The code you provided generates a 4x4 NumPy array of random numbers using the numpy.random.randn function,
#  and then calculates the mean of all the elements in the array using the mean() method of NumPy arrays.

# Here's a step-by-step breakdown of how the mean is calculated:

# Generate the random 4x4 array a using np.random.randn(4,4).
# Print the array to the console using print(a).
# Call the mean() method on the array a, which calculates the mean of all the elements in the array.
# The mean value is returned as the output of the mean() method.
# So, the mean of the array a is simply the average of all the values in the array.
print(a)
a.mean()


[0.15514119 0.63556156 0.36101127 0.26075231 0.71496431]


[ 1.26077347  1.06892621 -0.11160085  0.17790442]


0.5990008115178705


[[ 0.70241511 -0.2002568   0.07688772  0.54071023]
 [-0.66305938  0.64786058  0.29212458  0.72925207]
 [-0.21398524  0.94638945 -0.11013659 -1.0524436 ]
 [ 1.60671401  0.58605196  0.62219848  1.78972667]]


0.39377807750616095

In [33]:
# To calculate the mean of each row in the array a and store the results in a 1x4 matrix, you can use the mean() method again, 
#but this time specify the axis parameter to calculate the mean along each row. 
#Then, you can reshape the resulting array to a 1x4 matrix using the reshape() method.

a = np.random.randn(4,4)
print("Original array:")
print(a)
print("\n")

# Calculate the mean of each row along axis=1
row_means = a.mean(axis=1) 
print(row_means)
print("\n")

# Reshape the resulting array to a 1x4 matrix
row_means = row_means.reshape(4,1)

print("Row means:")
print(row_means)

Original array:
[[ 1.92570665 -0.91123738  0.7684629  -1.91481102]
 [-0.27848431  1.93559819  1.74690169 -0.91166555]
 [ 0.60653515 -0.28823077 -1.29050952  0.06407839]
 [-0.20494073 -0.99407474 -1.05092884  1.06144861]]


[-0.03296971  0.6230875  -0.22703169 -0.29712393]


Row means:
[[-0.03296971]
 [ 0.6230875 ]
 [-0.22703169]
 [-0.29712393]]


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.random.randn(4,5)

array([[-0.14629543,  0.17642487,  1.3585172 , -0.51594989,  1.09404496],
       [ 1.49209623, -1.0041559 , -2.02312721,  1.39923833,  0.40405734],
       [ 0.53561563, -1.83250926, -1.15205432, -0.72878912,  1.56398468],
       [-0.59769065,  0.09731023,  1.45210226, -0.60309129, -0.23681431]])

In [16]:
np.arange(0, 101) / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [17]:
np.linspace(0, 1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [18]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
matrix[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [20]:
matrix[0:3,1 ].reshape(3, 1)

array([[ 2],
       [ 7],
       [12]])

In [21]:
matrix[4]

array([21, 22, 23, 24, 25])

In [22]:
matrix[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
#Caclulate the sum of matrix mqtrix
matrix.sum()

325

In [24]:
#claculate the standard deviation of matrix
matrix.std()

7.211102550927978

In [25]:
sum_colums = matrix.sum(axis=0)
print(sum_colums)

[55 60 65 70 75]
